spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4GJNwSNdbvbv4qMUhYZk
      secret-key: zyc2td7zKSMK616s5YZlohOrRp8Px4
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com

  application:
    name: gulimall-third-party

server:
  port: 30000
